# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.0"

default_platform :android

platform :android do
  before_all do
    welcome
    git_pull
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to fir"
  lane :beta do
    gradle(task: "assembleStagingRelease")
    fir(
      apk_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      changelog: "test"
      )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

def welcome
  puts '
      ___              __           _     __
     /   |  ____  ____/ /________  (_)___/ /
    / /| | / __ \/ __  / ___/ __ \/ / __  / 
   / ___ |/ / / / /_/ / /  / /_/ / / /_/ /  
  /_/  |_/_/ /_/\__,_/_/   \____/_/\__,_/   
  '
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
